### ISSUE TITLE
Feature Request, LightTheme GithubCopilot text legibility

### ISSUE THREAD

**Issue by schwers** [yemreak/mindease-vscode-theme#1]
First off, I really like the themes! I found these on trending in `vscodethemes.com` and tried them out. Something does feel relaxing about using them. Thanks for the nice work on these!

My one major point of feedback is that code suggested by GithubCopilot (and some of the subheadlines in settings) is a very light, off-white, text that doesn't have enough contrast from the background color to read

e.g. in Solarized Light
<img width="430" alt="image" src="https://github.com/yemreak/mindease-vscode-theme/assets/54642384/e4c0ef56-925c-4a70-b2d4-21b51a48e558">

vs in A New Dawn
<img width="441" alt="image" src="https://github.com/yemreak/mindease-vscode-theme/assets/54642384/2782fc1a-fe0b-444d-a0a0-836193cc3259">

**Comment by yemreak** [comment]
Hello 👋

Firstly, Thank you for your suggestion. Light themes are experimental for now, but I'm planning and taking notes on suitable colors for them I will also note your request 🙃

Your request makes me happy :)

**Comment by yemreak** [comment]
I made complately new interface for light theme, and also this issue is gone.
<img width="567" alt="image" src="https://github.com/yemreak/mindease-vscode-theme/assets/49655146/60749351-5722-4678-8b2b-e42212be2392">

**Comment by schwers** [comment]
Sweet! I’ll try it out, that was speedy
