### ISSUE TITLE
SQL Syntax Highlighting Issue

### ISSUE THREAD

**Issue by FurkanDin** [yemreak/mindease-vscode-theme#3]
Thank you for your attention to this issue. I believe that improving SQL syntax highlighting will enhance the user experience for those using your theme with SQL code.

**Comment by yemreak** [comment]
<img width="340" alt="image" src="https://github.com/yemreak/mindease-vscode-theme/assets/49655146/e45d6654-2260-47b9-9ef1-54f222b13f04">
<img width="402" alt="image" src="https://github.com/yemreak/mindease-vscode-theme/assets/49655146/3111307b-da37-4186-b65d-bedbd0dfb66b">
